#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#include "tinyprintf.h"
#include "aws_clientcredential.h"


#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_CIPHERSUITES MBEDTLS_TLS_RSA_WITH_AES_128_CBC_SHA,MBEDTLS_TLS_RSA_WITH_AES_256_CBC_SHA

#if (USE_MQTT_BROKER == MQTT_BROKER_AWS_GREENGRASS)
#define MBEDTLS_SSL_MAX_CONTENT_LEN 1536
#elif (USE_MQTT_BROKER == MQTT_BROKER_AWS_IOT)
#define MBEDTLS_SSL_MAX_CONTENT_LEN 3072
#elif (USE_MQTT_BROKER == MQTT_BROKER_MOSQUITTO)
#define MBEDTLS_SSL_MAX_CONTENT_LEN 3072
#define MBEDTLS_SHA512_C
#endif

#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#define MBEDTLS_RSA_C
#define MBEDTLS_MD_C
#define MBEDTLS_MD5_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_OID_C
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_AES_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C

#define MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_MPI_WINDOW_SIZE 1
#define MBEDTLS_MPI_MAX_SIZE 256
#define MBEDTLS_SHA256_SMALLER
#define MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE

#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_STD_CALLOC
#define MBEDTLS_PLATFORM_STD_SNPRINTF
#define MBEDTLS_PLATFORM_STD_FREE
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_SNPRINTF_ALT

#include "mbedtls/check_config.h"

#endif /* MBEDTLS_CONFIG_H */

