#ifndef AVS_CONFIG_DEFAULTS_H
#define AVS_CONFIG_DEFAULTS_H

#include "../../library/utils/device_information.h"


#ifndef AVS_CONFIG_SERVER_ADDR
#error "AVS_CONFIG_SERVER_ADDR must be set"
#endif

#ifndef AVS_CONFIG_SERVER_PORT
#define AVS_CONFIG_SERVER_PORT          (11234)
#endif


#ifndef AVS_CONFIG_DIFFERENT_ACCOUNT
#define AVS_CONFIG_DIFFERENT_ACCOUNT    0
#endif

#ifndef AVS_CONFIG_SAMPLING_RATE
#define AVS_CONFIG_SAMPLING_RATE        SAMPLING_RATE_16KHZ
#endif

#ifndef AVS_CONFIG_AUDIO_BUFFER_SIZE
#define AVS_CONFIG_AUDIO_BUFFER_SIZE    (2048)
#endif

#ifndef AVS_CONFIG_SDCARD_BUFFER_SIZE
#define AVS_CONFIG_SDCARD_BUFFER_SIZE   (4096)
#endif

#ifndef AVS_CONFIG_RX_TIMEOUT
#define AVS_CONFIG_RX_TIMEOUT           (10)
#endif

#ifndef AVS_CONFIG_TX_TIMEOUT
#define AVS_CONFIG_TX_TIMEOUT           (10)
#endif

#ifndef AVS_CONFIG_MAX_RECORD_SIZE
#define AVS_CONFIG_MAX_RECORD_SIZE      (1024000)
#endif


#ifndef AVS_CONFIG_AUDIO_SEND_FORMAT
#define AVS_CONFIG_AUDIO_SEND_FORMAT    (DEVICE_CAPABILITIES_FORMAT_RAW)
#endif

#ifndef AVS_CONFIG_AUDIO_SEND_BITDEPTH
#define AVS_CONFIG_AUDIO_SEND_BITDEPTH  (DEVICE_CAPABILITIES_BITDEPTH_8)
#endif

#ifndef AVS_CONFIG_AUDIO_SEND_BITRATE
#define AVS_CONFIG_AUDIO_SEND_BITRATE   (DEVICE_CAPABILITIES_BITRATE_16000)
#endif

#ifndef AVS_CONFIG_AUDIO_SEND_CHANNEL
#define AVS_CONFIG_AUDIO_SEND_CHANNEL   (DEVICE_CAPABILITIES_CHANNEL_1)
#endif


#ifndef AVS_CONFIG_AUDIO_RECV_FORMAT
#define AVS_CONFIG_AUDIO_RECV_FORMAT    (DEVICE_CAPABILITIES_FORMAT_RAW)
#endif

#ifndef AVS_CONFIG_AUDIO_RECV_BITDEPTH
#define AVS_CONFIG_AUDIO_RECV_BITDEPTH  (DEVICE_CAPABILITIES_BITDEPTH_8)
#endif

#ifndef AVS_CONFIG_AUDIO_RECV_BITRATE
#define AVS_CONFIG_AUDIO_RECV_BITRATE   (DEVICE_CAPABILITIES_BITRATE_16000)
#endif

#ifndef AVS_CONFIG_AUDIO_RECV_CHANNEL
#define AVS_CONFIG_AUDIO_RECV_CHANNEL   (DEVICE_CAPABILITIES_CHANNEL_1)
#endif


#endif // AVS_CONFIG_DEFAULTS_H
