#ifndef AVS_CONFIG_DEFAULTS_H
#define AVS_CONFIG_DEFAULTS_H


#ifndef AVS_CONFIG_SERVER_ADDR
#error "AVS_CONFIG_SERVER_ADDR must be set"
#endif

#ifndef AVS_CONFIG_SERVER_PORT
#define AVS_CONFIG_SERVER_PORT          (11234)
#endif

#ifndef AVS_CONFIG_SAMPLING_RATE
#define AVS_CONFIG_SAMPLING_RATE        SAMPLING_RATE_44100HZ
#endif

#ifndef AVS_CONFIG_RXTX_BUFFER_SIZE
#define AVS_CONFIG_RXTX_BUFFER_SIZE     (1460*2)
#endif

#ifndef AVS_CONFIG_AUDIO_BUFFER_SIZE
#define AVS_CONFIG_AUDIO_BUFFER_SIZE    (2048)
#endif

#ifndef AVS_CONFIG_RX_TIMEOUT
#define AVS_CONFIG_RX_TIMEOUT           (20)
#endif

#ifndef AVS_CONFIG_TX_TIMEOUT
#define AVS_CONFIG_TX_TIMEOUT           (15)
#endif

#ifndef AVS_CONFIG_MAX_RECORD_SIZE
#define AVS_CONFIG_MAX_RECORD_SIZE      (4096000)
#endif


#endif // AVS_CONFIG_DEFAULTS_H
