#ifndef AVS_CONFIG_DEFAULTS_H
#define AVS_CONFIG_DEFAULTS_H


#ifndef AVS_CONFIG_SERVER_ADDR
#error "AVS_CONFIG_SERVER_ADDR must be set"
#endif

#ifndef AVS_CONFIG_SERVER_PORT
#define AVS_CONFIG_SERVER_PORT          (11234)
#endif

#ifndef AVS_CONFIG_DIFFERENT_ACCOUNT
#define AVS_CONFIG_DIFFERENT_ACCOUNT    0
#endif

#ifndef AVS_CONFIG_SAMPLING_RATE
#define AVS_CONFIG_SAMPLING_RATE        SAMPLING_RATE_16KHZ
#endif

#ifndef AVS_CONFIG_AUDIO_BUFFER_SIZE
#define AVS_CONFIG_AUDIO_BUFFER_SIZE    (2048)
#endif

#ifndef AVS_CONFIG_SDCARD_BUFFER_SIZE
#define AVS_CONFIG_SDCARD_BUFFER_SIZE   (4096)
#endif

#ifndef AVS_CONFIG_RX_TIMEOUT
#define AVS_CONFIG_RX_TIMEOUT           (10)
#endif

#ifndef AVS_CONFIG_TX_TIMEOUT
#define AVS_CONFIG_TX_TIMEOUT           (10)
#endif

#ifndef AVS_CONFIG_MAX_RECORD_SIZE
#define AVS_CONFIG_MAX_RECORD_SIZE      (1024000)
#endif


#endif // AVS_CONFIG_DEFAULTS_H
